name: Greeting on variable day

on: 
 workflow_dispatch

jobs:
  greeting_job:
     runs-on: ubuntu-latest
     env: 
       Greeting : Hello
     steps:
       - name: "Say Hello world, it's Monday"
         run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
         env:
           First_Name: Mona
