name : Listening for repository_dispatch

on:
  repository_dispatch:
    types: [run-tests, deploy-to-prod]

jobs:
  runs: 
    runs-on: ubuntu-latest
    steps:
      - name: Echo the payload
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Payload value: ${{ github.event.client_payload.env }}"
        
        
