name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  welcome:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment "$PR_URL" --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Add label when approved
        uses: pullreminders/label-when-approved-action@main
        env: 
          APPROVALS: "1"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ADD_LABEL: "approved"
